"use client";
import ModulePage from "@/components/ui/ModulePage";
import HolographicCard from "@/components/ui/HolographicCard";
import { PieChart, Download, FileText } from "lucide-react";
import styles from "./reports.module.css";


export default function CRMReports() {
    return (
        <ModulePage title="Intelligence Reports" subtitle="Automated data synthesis and strategic business reporting.">
            <div className={styles.grid}>
                <HolographicCard title="Quarterly Growth" variant="neon">
                    <div className={styles.placeholder}>
                        <PieChart size={64} className={styles.icon} />
                        <p>Report #QR-004 is currently being generated by the AI OS.</p>
                    </div>
                </HolographicCard>

                <HolographicCard title="Available Downloads" interactive={false}>
                    <div className={styles.list}>
                        <div className={styles.reportItem}>
                            <FileText size={18} />
                            <div className={styles.info}>
                                <p>Market_Sentiment_Lagos.pdf</p>
                                <span>Generated 2 days ago</span>
                            </div>
                            <Download size={18} className={styles.download} />
                        </div>
                    </div>
                </HolographicCard>
            </div>
        </ModulePage>
    );
}
